function [audio_data, Fs] = slice_audio(audio_filepath,time_slice,from_middle)      
    %Extracts T seconds from a given song (as explicitly required in question 1 and 3)

    %Usage: 
    %Inputs: provide path to file, amount of time you want to extract and
    %a boolean value for if you want to take out information from the
    %middle or from the beginning (no other location supported yet)
    
    %Outputs:
    %audio_data = audio_data
    
    %Software switch to indicate we're working with part 3 of final project
    part3 = 1;
 
    %Read audio file
    [audio_data, Fs] = audioread(audio_filepath);
    
    %Form audio object to easily collect data about song
    song = audioplayer(audio_data,Fs);
    
    %Song duration in seconds
    songDuration = song.TotalSamples/song.SampleRate;
    
    %Assume song will always be long enough (for now)
    song_is_long_enough = 1;

    %{
    -----------------------SLICE AUDIO MODIFIED TO EXTRACT 2 MIN FROM SONG-----------------------
    %}
    
    %Criteria for a good song: we can extract two minutes starting at
    %middle of song
    if from_middle
        song_is_long_enough = ((songDuration/2) >= time_slice);
    end
    

    if song_is_long_enough && from_middle && part3
        %We can extract two minutes starting at middle of song.

        %Take two min of audio data from song_path starting from the middle
        %{
            Definitions of variables below:

            songObject - audio player object generated by slice_audio()
            fs = sampling rate of song
            start = frame at middle of song
            stop = end of two minute sample
        %}

        if not(from_middle)
            %Extract information from beginning to time "time_sample"
            start = 1;                          %Indicates beginning
            stop = song.SampleRate*time_slice;  %Ending time defined by user  
        else
            %Take from the middle
            start = song.TotalSamples/2;
            %End at specified time after middle of song
            stop = start + song.SampleRate*time_slice;
        end
        
        
    elseif part3 && ~song_is_long_enough
        %If working on part 3, and song is not long enough...
        %Cannot extract two minutes starting from middle. Use the whole song.
        start = 1;
        stop = song.TotalSamples;
    elseif ~part3 && ~from_miffle
        %Normal audio slice. Take amount of time specified by user starting
        %at beginning
        start = 1;
        stop = song.SampleRate*time_slice;
    end
    
    %Slice the audio
    try
        audio_data = audio_data(start:stop);
    catch
        warning('Could not slice audio. Is song long enough?')
    end
end